-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'BOOKING_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE 'BOOKING_IN_PROGRESS';
ALTER TYPE "NotificationType" ADD VALUE 'BOOKING_COMPLETED';
ALTER TYPE "NotificationType" ADD VALUE 'PAYMENT_REFUNDED';
ALTER TYPE "NotificationType" ADD VALUE 'PROVIDER_APPLICATION_SUBMITTED';
ALTER TYPE "NotificationType" ADD VALUE 'PROVIDER_APPLICATION_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE 'PROVIDER_APPLICATION_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE 'LEAD_ACCEPTED';
ALTER TYPE "NotificationType" ADD VALUE 'WELCOME';
ALTER TYPE "NotificationType" ADD VALUE 'ACCOUNT_UPDATED';
ALTER TYPE "NotificationType" ADD VALUE 'ANNOUNCEMENT';
ALTER TYPE "NotificationType" ADD VALUE 'PASSWORD_CHANGED';
ALTER TYPE "NotificationType" ADD VALUE 'REVIEW_REQUESTED';
